#!/usr/bin/env python3
"""
Import blog posts from Supabase backup file to PostgreSQL.
Extracts data from the 'mutters' table.
"""

import os
import re
import psycopg2
from datetime import datetime
from typing import List, Tuple

DB_CONFIG = {
    'host': os.getenv('POSTGRES_HOST', 'localhost'),
    'port': os.getenv('POSTGRES_PORT', '5432'),
    'user': os.getenv('POSTGRES_USER', 'blog_user'),
    'password': os.getenv('POSTGRES_PASSWORD', 'blog_password'),
    'database': os.getenv('POSTGRES_DB', 'blog_db')
}

def parse_backup_file(backup_file: str) -> List[Tuple]:
    """
    Parse Supabase backup file and extract mutters data.
    Format: id, author_id, created_at, updated_at, content, title, summary, is_private
    """
    with open(backup_file, 'r', encoding='utf-8') as f:
        content = f.read()

    # Find the COPY section for mutters
    copy_pattern = r'COPY public\.mutters.*?FROM stdin;(.*?)\\\\.'
    match = re.search(copy_pattern, content, re.DOTALL)

    if not match:
        print("Error: Could not find mutters data in backup file")
        return []

    data_lines = match.group(1).strip().split('\n')

    posts = []
    for line in data_lines:
        if not line.strip():
            continue

        # Parse tab-separated values
        parts = line.split('\t')
        if len(parts) < 8:
            continue

        post_id, author_id, created_at, updated_at, content, title, summary, is_private = parts

        # Parse timestamp (remove +00 timezone)
        try:
            created_at = datetime.fromisoformat(created_at.replace('+00', ''))
        except:
            created_at = datetime.now()

        # Handle \N (NULL) values
        if updated_at == '\\N':
            updated_at = None
        else:
            try:
                updated_at = datetime.fromisoformat(updated_at.replace('+00', ''))
            except:
                updated_at = None

        if summary == '\\N':
            summary = None

        is_private = is_private.lower() == 't'

        # Skip private posts (commented out to import all)
        # if is_private:
        #     print(f"  Skipping private post: {title}")
        #     continue

        posts.append((post_id, created_at, updated_at, content, title, summary, is_private))

    return posts

def generate_slug(title: str, created_at: datetime) -> str:
    """Generate URL-friendly slug from title"""
    if not title or title == 'no name':
        # Use date if no meaningful title
        return f"post-{created_at.strftime('%Y%m%d-%H%M%S')}"

    # Clean title for slug
    slug = title.lower()
    # Replace Chinese/special characters
    slug = re.sub(r'[^\w\s-]', '', slug)
    slug = re.sub(r'[\s_]+', '-', slug)
    slug = slug.strip('-')

    # If slug is empty after cleaning (e.g., pure Chinese), use date
    if not slug:
        slug = f"post-{created_at.strftime('%Y%m%d')}"

    return slug[:100]  # Limit length

def extract_excerpt(content: str, max_length: int = 150) -> str:
    """Extract excerpt from content"""
    # Clean markdown
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', content)  # Remove bold
    text = re.sub(r'\*(.+?)\*', r'\1', text)  # Remove italic
    text = re.sub(r'\n+', ' ', text)  # Remove newlines
    text = text.strip()

    if len(text) > max_length:
        text = text[:max_length] + '...'

    return text

def import_mutters(backup_file: str, author_id: int = 1):
    """Import mutters from Supabase backup"""
    print(f"Parsing backup file: {backup_file}")
    posts = parse_backup_file(backup_file)

    if not posts:
        print("No posts found in backup file")
        return

    print(f"Found {len(posts)} posts to import")

    conn = psycopg2.connect(**DB_CONFIG)
    cursor = conn.cursor()

    posts_imported = 0
    posts_skipped = 0

    for post_id, created_at, updated_at, content, title, summary, is_private in posts:
        try:
            # Generate slug
            slug = generate_slug(title, created_at)

            # Check for duplicate slug
            cursor.execute("SELECT id FROM posts WHERE slug = %s", (slug,))
            if cursor.fetchone():
                # Make slug unique by adding timestamp
                slug = f"{slug}-{created_at.strftime('%H%M%S')}"

            # Generate excerpt if no summary
            excerpt = summary if summary else extract_excerpt(content)

            # Check if content looks like it might be AI-generated (heuristic)
            is_ai_generated = any(marker in content.lower() for marker in
                                  ['generated by', 'ai assistant', 'chatgpt', 'claude'])

            # Insert post (is_draft set to is_private)
            cursor.execute("""
                INSERT INTO posts (
                    title, slug, content, excerpt, author_id,
                    is_ai_generated, is_draft, created_at, updated_at
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING id
            """, (
                title if title != 'no name' else f"Untitled - {created_at.strftime('%Y-%m-%d')}",
                slug,
                content,
                excerpt,
                author_id,
                is_ai_generated,
                is_private,  # is_draft = is_private
                created_at,
                updated_at if updated_at else created_at
            ))

            new_post_id = cursor.fetchone()[0]

            conn.commit()
            posts_imported += 1
            print(f"✓ Imported: {title} -> {slug}")

        except Exception as e:
            conn.rollback()
            print(f"✗ Error importing '{title}': {e}")
            posts_skipped += 1

    cursor.close()
    conn.close()

    print(f"\n=== Import Complete ===")
    print(f"Posts imported: {posts_imported}")
    print(f"Posts skipped: {posts_skipped}")
    print(f"Total posts: {len(posts)}")

if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: python import_supabase_backup.py <backup_file>")
        sys.exit(1)

    backup_file = sys.argv[1]

    if not os.path.exists(backup_file):
        print(f"Error: File '{backup_file}' not found")
        sys.exit(1)

    print("=" * 60)
    print("Supabase Backup Import Tool")
    print("=" * 60)
    print(f"Backup file: {backup_file}")
    print(f"Database: {DB_CONFIG['host']}:{DB_CONFIG['port']}/{DB_CONFIG['database']}")
    print()

    import_mutters(backup_file)
